services:
  - type: web
    name: spotify-party
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SPOTIFY_CLIENT_ID
        value: 3e79328c5f814b52a27d64e50a140404
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./spotify_party.db